-- =========================================================================
-- 042 - Listas de precios (feature por empresa)
-- =========================================================================
-- ADITIVO: crea 3 tablas nuevas + sus RLS + registra el modulo. No toca tablas
-- existentes (la asignacion cliente->lista va en una tabla mapa, no en `clientes`).
--
--   listas_precios          -> la lista (tipo 'porcentaje' o 'individual')
--   listas_precios_detalle  -> precio por producto (solo tipo 'individual')
--   cliente_lista_precio    -> que lista usa cada cliente (1 por cliente)
--
-- El modulo "Listas de Precios" nace DESHABILITADO por empresa (no esta en
-- MODULOS_BASE): el super-admin lo habilita desde /plataforma -> Modulos.
-- Requiere el script 017 (funcion app_current_tenant).
-- =========================================================================

-- 1) Listas
CREATE TABLE IF NOT EXISTS public.listas_precios (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint NOT NULL,
  nombre          text   NOT NULL,
  tipo            text   NOT NULL DEFAULT 'porcentaje',  -- 'porcentaje' | 'individual'
  -- % de DESCUENTO sobre el precio base (tipo 'porcentaje'). Siempre baja el
  -- precio: ej. 5 = 5% menos. La app usa el valor absoluto. Solo si tipo='porcentaje'.
  porcentaje      numeric NOT NULL DEFAULT 0,
  activo          boolean NOT NULL DEFAULT true,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.listas_precios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS listas_precios_tenant ON public.listas_precios;
CREATE POLICY listas_precios_tenant ON public.listas_precios
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- 2) Detalle: precio especifico por producto (tipo 'individual')
CREATE TABLE IF NOT EXISTS public.listas_precios_detalle (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint NOT NULL,
  lista_id        bigint NOT NULL REFERENCES public.listas_precios(id) ON DELETE CASCADE,
  producto_id     bigint NOT NULL,
  precio          numeric NOT NULL,
  UNIQUE (lista_id, producto_id)
);
ALTER TABLE public.listas_precios_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS listas_precios_detalle_tenant ON public.listas_precios_detalle;
CREATE POLICY listas_precios_detalle_tenant ON public.listas_precios_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- 3) Asignacion de lista a cliente (1 lista por cliente)
CREATE TABLE IF NOT EXISTS public.cliente_lista_precio (
  cliente_id      bigint PRIMARY KEY,
  razon_social_id bigint NOT NULL,
  lista_id        bigint NOT NULL REFERENCES public.listas_precios(id) ON DELETE CASCADE
);
ALTER TABLE public.cliente_lista_precio ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cliente_lista_precio_tenant ON public.cliente_lista_precio;
CREATE POLICY cliente_lista_precio_tenant ON public.cliente_lista_precio
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- 4) Registrar el modulo (debe calzar EXACTO con MODULOS de lib/constants/modulos.ts)
INSERT INTO public.modulos (nombre) VALUES ('Listas de Precios')
ON CONFLICT (nombre) DO NOTHING;
