-- =========================================================================
-- 046 - Produccion FASE 1: Materiales de fabricacion (catalogo + compra +
--       inventario/valoracion), sistema PROPIO (no toca `productos`).
-- =========================================================================
-- ADITIVO: crea tablas nuevas + sus RLS + RPCs de stock de material + registra
-- 3 modulos. NO toca tablas existentes (regla del proyecto).
--
--   materiales                     -> catalogo de materia prima (espejo de productos)
--   materiales_compras_encabezado  -> compra de material a proveedor
--   materiales_compras_detalle     -> lineas de la compra
--   materiales_movimientos         -> kardex de material (stock = SUMA de cantidad)
--
-- El costo promedio y el stock global del material se mueven SOLO por las RPCs
-- `mat_ajustar_stock` / `mat_aplicar_entrada` (analogas al script 018 pero
-- contra `materiales`). El stock por almacen/localizacion se DERIVA sumando
-- `materiales_movimientos.cantidad` (igual que transacciones_inventario).
--
-- Los 3 modulos ('Materiales','Compra de Materiales','Inventario de Materiales')
-- nacen DESHABILITADOS por empresa (no estan en MODULOS_BASE): el super-admin
-- los habilita desde /plataforma -> Modulos. Requiere el script 017.
-- =========================================================================

-- 1) Catalogo de materiales
CREATE TABLE IF NOT EXISTS public.materiales (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  nombre          text    NOT NULL,
  codigo          text,
  unidad_medida   text    NOT NULL DEFAULT 'unidad',
  costo_promedio  numeric(14,4) NOT NULL DEFAULT 0,
  stock_total     numeric(14,4) NOT NULL DEFAULT 0,
  activo          boolean NOT NULL DEFAULT true,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz
);
ALTER TABLE public.materiales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS materiales_tenant ON public.materiales;
CREATE POLICY materiales_tenant ON public.materiales
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- 2) Compra de material (encabezado)
CREATE TABLE IF NOT EXISTS public.materiales_compras_encabezado (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id    bigint  NOT NULL,
  proveedor_id       bigint,
  fecha_orden        timestamptz,
  fecha_tentativa    date,
  moneda             text    NOT NULL DEFAULT 'LPS',
  tasa_cambio        numeric(12,4) NOT NULL DEFAULT 1,
  costos_importacion numeric(14,2) NOT NULL DEFAULT 0,
  impuestos_compra   numeric(14,2) NOT NULL DEFAULT 0,
  otros_costos       numeric(14,2) NOT NULL DEFAULT 0,
  total_local        numeric(14,2) NOT NULL DEFAULT 0,
  estado             text    NOT NULL DEFAULT 'Pendiente',  -- Pendiente | Recibida | Cancelada
  usuario            text,
  created_at         timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.materiales_compras_encabezado ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS materiales_compras_encabezado_tenant ON public.materiales_compras_encabezado;
CREATE POLICY materiales_compras_encabezado_tenant ON public.materiales_compras_encabezado
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- 3) Compra de material (detalle)
CREATE TABLE IF NOT EXISTS public.materiales_compras_detalle (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id             bigint  NOT NULL,
  compra_id                   bigint  NOT NULL REFERENCES public.materiales_compras_encabezado(id) ON DELETE CASCADE,
  material_id                 bigint  NOT NULL REFERENCES public.materiales(id),
  cantidad                    numeric(14,4) NOT NULL,
  cantidad_recibida           numeric(14,4) NOT NULL DEFAULT 0,
  costo_unitario_moneda_origen numeric(14,4) NOT NULL DEFAULT 0,
  costo_final_local           numeric(14,4),
  usuario                     text,
  created_at                  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.materiales_compras_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS materiales_compras_detalle_tenant ON public.materiales_compras_detalle;
CREATE POLICY materiales_compras_detalle_tenant ON public.materiales_compras_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_materiales_compras_detalle_compra
  ON public.materiales_compras_detalle (razon_social_id, compra_id);

-- 4) Kardex de material (stock por localizacion = SUMA de cantidad)
CREATE TABLE IF NOT EXISTS public.materiales_movimientos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  material_id     bigint  NOT NULL REFERENCES public.materiales(id),
  almacen_id      bigint,
  localizacion_id bigint,
  -- Texto libre: 'Entrada Compra Material' | 'Consumo Produccion' | 'Ajuste' |
  --              'Traslado Entrada' | 'Traslado Salida'
  tipo_movimiento text    NOT NULL,
  cantidad        numeric(14,4) NOT NULL,   -- + entrada, - salida
  costo_unitario  numeric(14,4) NOT NULL DEFAULT 0,
  referencia_id   bigint,
  fecha           timestamptz,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.materiales_movimientos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS materiales_movimientos_tenant ON public.materiales_movimientos;
CREATE POLICY materiales_movimientos_tenant ON public.materiales_movimientos
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_materiales_movimientos_material
  ON public.materiales_movimientos (razon_social_id, material_id);
CREATE INDEX IF NOT EXISTS idx_materiales_movimientos_fecha
  ON public.materiales_movimientos (razon_social_id, fecha DESC);

-- 5) RPCs atomicas de stock de material (analogas al script 018, sobre materiales)
--    SECURITY INVOKER: la RLS de `materiales` aplica (no tocan otro tenant).
CREATE OR REPLACE FUNCTION public.mat_ajustar_stock(
  p_material_id bigint,
  p_delta       numeric
)
RETURNS numeric
LANGUAGE sql
AS $$
  UPDATE public.materiales
  SET stock_total = COALESCE(stock_total, 0) + p_delta,
      updated_at  = now()
  WHERE id = p_material_id
  RETURNING stock_total;
$$;
REVOKE ALL ON FUNCTION public.mat_ajustar_stock(bigint, numeric) FROM public;
GRANT EXECUTE ON FUNCTION public.mat_ajustar_stock(bigint, numeric) TO authenticated;

CREATE OR REPLACE FUNCTION public.mat_aplicar_entrada(
  p_material_id    bigint,
  p_cantidad       numeric,
  p_costo_unitario numeric
)
RETURNS TABLE (stock_total numeric, costo_promedio numeric)
LANGUAGE sql
AS $$
  UPDATE public.materiales m
  SET
    costo_promedio = CASE
      WHEN COALESCE(m.stock_total, 0) + p_cantidad > 0
        THEN ((COALESCE(m.stock_total, 0) * COALESCE(m.costo_promedio, 0))
              + (p_cantidad * p_costo_unitario))
             / (COALESCE(m.stock_total, 0) + p_cantidad)
      ELSE p_costo_unitario
    END,
    stock_total = COALESCE(m.stock_total, 0) + p_cantidad,
    updated_at  = now()
  WHERE m.id = p_material_id
  RETURNING m.stock_total, m.costo_promedio;
$$;
REVOKE ALL ON FUNCTION public.mat_aplicar_entrada(bigint, numeric, numeric) FROM public;
GRANT EXECUTE ON FUNCTION public.mat_aplicar_entrada(bigint, numeric, numeric) TO authenticated;

-- 6) Registrar los 3 modulos (deben calzar EXACTO con MODULOS de constants)
INSERT INTO public.modulos (nombre) VALUES
  ('Materiales'),
  ('Compra de Materiales'),
  ('Inventario de Materiales')
ON CONFLICT (nombre) DO NOTHING;
