-- =========================================================================
-- 047 - Produccion FASE 2: Recetas / MRP (BOM del producto fabricado)
-- =========================================================================
-- ADITIVO: crea 2 tablas nuevas + RLS + registra el modulo "Recetas". NO toca
-- tablas existentes. Requiere el script 046 (materiales) y 017 (RLS).
--
--   produccion_recetas            -> 1 receta por producto FABRICADO (marca que
--                                    ese producto se fabrica). Estandar de
--                                    produccion (u/min) + factores de costo por
--                                    unidad (energia, mano de obra, overhead) +
--                                    costo unitario estimado (cache informativo).
--   produccion_receta_materiales  -> lineas de la receta: material + consumo por
--                                    unidad producida.
--
-- El producto fabricado sigue siendo una fila normal en `productos`; su costo
-- REAL se fija al recibir cada corrida (Fase 6). Aqui solo se estima.
-- El modulo "Recetas" nace DESHABILITADO por empresa (no esta en MODULOS_BASE).
-- =========================================================================

-- 1) Receta (una por producto fabricado)
CREATE TABLE IF NOT EXISTS public.produccion_recetas (
  id                            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id               bigint  NOT NULL,
  producto_id                   bigint  NOT NULL,
  estandar_unidades_por_minuto  numeric(12,4) NOT NULL DEFAULT 0,
  -- Factores de costo POR UNIDAD producida (Lempiras).
  costo_energia                 numeric(14,4) NOT NULL DEFAULT 0,
  costo_mano_obra               numeric(14,4) NOT NULL DEFAULT 0,
  costo_overhead                numeric(14,4) NOT NULL DEFAULT 0,
  -- Cache: Sum(consumo x costo_promedio material) + factores. Informativo.
  costo_unitario_estimado       numeric(14,4) NOT NULL DEFAULT 0,
  activo                        boolean NOT NULL DEFAULT true,
  usuario                       text,
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_at                    timestamptz,
  -- Un producto tiene a lo sumo una receta por empresa.
  UNIQUE (razon_social_id, producto_id)
);
ALTER TABLE public.produccion_recetas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_recetas_tenant ON public.produccion_recetas;
CREATE POLICY produccion_recetas_tenant ON public.produccion_recetas
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- 2) Lineas de la receta (materiales y su consumo por unidad)
CREATE TABLE IF NOT EXISTS public.produccion_receta_materiales (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id    bigint  NOT NULL,
  receta_id          bigint  NOT NULL REFERENCES public.produccion_recetas(id) ON DELETE CASCADE,
  material_id        bigint  NOT NULL REFERENCES public.materiales(id),
  consumo_por_unidad numeric(14,6) NOT NULL,
  usuario            text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (receta_id, material_id)
);
ALTER TABLE public.produccion_receta_materiales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_receta_materiales_tenant ON public.produccion_receta_materiales;
CREATE POLICY produccion_receta_materiales_tenant ON public.produccion_receta_materiales
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_receta_materiales_receta
  ON public.produccion_receta_materiales (razon_social_id, receta_id);

-- 3) Registrar el modulo (debe calzar EXACTO con MODULOS de constants)
INSERT INTO public.modulos (nombre) VALUES ('Recetas')
ON CONFLICT (nombre) DO NOTHING;
