-- =========================================================================
-- 048 - Produccion FASE 3: Marca "producto fabricado" + Ordenes de produccion
-- =========================================================================
-- ADITIVO: crea 2 tablas nuevas + RLS + registra el modulo "Ordenes de
-- Produccion". NO toca `productos` (la marca de fabricado va en una tabla mapa,
-- igual que clientes_inactivos / producto_grupo_tallas). Requiere 046, 047, 017.
--
--   productos_fabricados  -> marca los productos de `productos` que se FABRICAN.
--                            Se activa desde el editor de Producto. Recetas y
--                            Ordenes usan esta marca.
--   produccion_ordenes    -> orden de produccion (que producto, cuanto, para
--                            cuando). Congela receta_id si el producto la tiene.
--
-- Estados de la orden: Abierta | En Proceso | Cerrada | Cancelada.
-- El modulo nace DESHABILITADO por empresa (no esta en MODULOS_BASE).
-- =========================================================================

-- 1) Marca de producto fabricado (mapa; no toca `productos`)
CREATE TABLE IF NOT EXISTS public.productos_fabricados (
  producto_id     bigint  PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.productos_fabricados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS productos_fabricados_tenant ON public.productos_fabricados;
CREATE POLICY productos_fabricados_tenant ON public.productos_fabricados
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- 2) Ordenes de produccion
CREATE TABLE IF NOT EXISTS public.produccion_ordenes (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id   bigint  NOT NULL,
  producto_id       bigint  NOT NULL,
  receta_id         bigint,             -- congelada al crear (si el producto tiene receta)
  cantidad_objetivo numeric(14,4) NOT NULL,
  fecha_objetivo    date,
  notas             text,
  estado            text    NOT NULL DEFAULT 'Abierta',  -- Abierta | En Proceso | Cerrada | Cancelada
  usuario           text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz
);
ALTER TABLE public.produccion_ordenes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_ordenes_tenant ON public.produccion_ordenes;
CREATE POLICY produccion_ordenes_tenant ON public.produccion_ordenes
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_ordenes_estado
  ON public.produccion_ordenes (razon_social_id, estado, created_at DESC);

-- 3) Registrar el modulo (debe calzar EXACTO con MODULOS de constants)
INSERT INTO public.modulos (nombre) VALUES ('Ordenes de Produccion')
ON CONFLICT (nombre) DO NOTHING;
