-- =========================================================================
-- 049 - Produccion FASE 4: Control de piso (corridas de produccion)
-- =========================================================================
-- ADITIVO: crea 3 tablas nuevas + RLS + registra el modulo "Control de Piso".
-- NO toca tablas existentes. Requiere 046 (materiales), 047 (recetas),
-- 048 (ordenes), 017 (RLS).
--
--   produccion_corridas          -> una corrida/lote por orden (varias por orden).
--                                   Horas, unidades buenas/defectuosas/procesadas,
--                                   paros, tiempo planificado, novedades, snapshots
--                                   de costo, estado.
--   produccion_corrida_defectos  -> motivos de las unidades defectuosas.
--   produccion_corrida_consumos  -> bitacora del descuento de materiales de la
--                                   corrida (cabecera). El kardex real vive en
--                                   materiales_movimientos ('Consumo Produccion').
--
-- El consumo = receta x unidades PROCESADAS (buenas + defectuosas). El costo
-- unitario real = (costo materiales + costo factores) / unidades_buenas.
-- Estados de la corrida: Registrada | Ejecutada | Recibida | Cancelada.
-- El modulo nace DESHABILITADO por empresa (no esta en MODULOS_BASE).
-- =========================================================================

-- 1) Corridas de produccion
CREATE TABLE IF NOT EXISTS public.produccion_corridas (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id             bigint  NOT NULL,
  orden_id                    bigint  NOT NULL REFERENCES public.produccion_ordenes(id) ON DELETE CASCADE,
  producto_id                 bigint  NOT NULL,       -- denormalizado desde la orden
  hora_inicio                 timestamptz,
  hora_fin                    timestamptz,
  unidades_buenas             numeric(14,4) NOT NULL DEFAULT 0,
  unidades_defectuosas        numeric(14,4) NOT NULL DEFAULT 0,
  unidades_procesadas         numeric(14,4) NOT NULL DEFAULT 0,  -- buenas + defectuosas
  paros_minutos               numeric(12,2) NOT NULL DEFAULT 0,
  tiempo_planificado_minutos  numeric(12,2),
  novedades                   text,
  costo_materiales_total      numeric(14,4) NOT NULL DEFAULT 0,
  costo_factores_total        numeric(14,4) NOT NULL DEFAULT 0,
  costo_unitario_real         numeric(14,4) NOT NULL DEFAULT 0,
  estado                      text    NOT NULL DEFAULT 'Registrada',  -- Registrada|Ejecutada|Recibida|Cancelada
  usuario                     text,
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz
);
ALTER TABLE public.produccion_corridas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_corridas_tenant ON public.produccion_corridas;
CREATE POLICY produccion_corridas_tenant ON public.produccion_corridas
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_corridas_orden
  ON public.produccion_corridas (razon_social_id, orden_id);
CREATE INDEX IF NOT EXISTS idx_produccion_corridas_fecha
  ON public.produccion_corridas (razon_social_id, created_at DESC);

-- 2) Motivos de defecto de una corrida
CREATE TABLE IF NOT EXISTS public.produccion_corrida_defectos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  corrida_id      bigint  NOT NULL REFERENCES public.produccion_corridas(id) ON DELETE CASCADE,
  motivo          text    NOT NULL,
  cantidad        numeric(14,4) NOT NULL,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.produccion_corrida_defectos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_corrida_defectos_tenant ON public.produccion_corrida_defectos;
CREATE POLICY produccion_corrida_defectos_tenant ON public.produccion_corrida_defectos
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_corrida_defectos_corrida
  ON public.produccion_corrida_defectos (razon_social_id, corrida_id);

-- 3) Bitacora del consumo de materiales por corrida
CREATE TABLE IF NOT EXISTS public.produccion_corrida_consumos (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id    bigint  NOT NULL,
  corrida_id         bigint  NOT NULL REFERENCES public.produccion_corridas(id) ON DELETE CASCADE,
  material_id        bigint  NOT NULL REFERENCES public.materiales(id),
  cantidad_consumida numeric(14,6) NOT NULL,
  costo_unitario     numeric(14,4) NOT NULL,
  costo_total        numeric(14,4) NOT NULL,
  usuario            text,
  created_at         timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.produccion_corrida_consumos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_corrida_consumos_tenant ON public.produccion_corrida_consumos;
CREATE POLICY produccion_corrida_consumos_tenant ON public.produccion_corrida_consumos
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_corrida_consumos_corrida
  ON public.produccion_corrida_consumos (razon_social_id, corrida_id);

-- 4) Registrar el modulo (debe calzar EXACTO con MODULOS de constants)
INSERT INTO public.modulos (nombre) VALUES ('Control de Piso')
ON CONFLICT (nombre) DO NOTHING;
