-- =========================================================================
-- 051 - Produccion FASE 6: Recepcion de producto terminado
-- =========================================================================
-- ADITIVO: crea 1 tabla nueva + RLS + registra el modulo "Recepcion de
-- Produccion". NO toca tablas existentes. Requiere 046-049 y 017.
--
--   produccion_recepciones -> confirma una corrida EJECUTADA y recibe el
--                             producto terminado al inventario. Guarda a que
--                             almacen/localizacion entro, cuantas unidades
--                             (las BUENAS) y con que costo unitario real, mas el
--                             id de la transaccion de inventario generada.
--
-- Al recibir: inserta en `transacciones_inventario` (tipo 'Entrada Produccion',
-- texto libre - sin ALTER) y suma stock + costo del producto via
-- `aplicar_entrada_compra` (promedio ponderado, como una compra). Guarda anti
-- doble-recepcion (una corrida se recibe una sola vez).
-- El modulo nace DESHABILITADO por empresa (no esta en MODULOS_BASE).
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.produccion_recepciones (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id     bigint  NOT NULL,
  corrida_id          bigint  NOT NULL REFERENCES public.produccion_corridas(id) ON DELETE CASCADE,
  producto_id         bigint  NOT NULL,
  almacen_id          bigint  NOT NULL,
  localizacion_id     bigint  NOT NULL,
  cantidad            numeric(14,4) NOT NULL,
  costo_unitario_real numeric(14,4) NOT NULL,
  transaccion_id      bigint,
  usuario             text,
  created_at          timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.produccion_recepciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_recepciones_tenant ON public.produccion_recepciones;
CREATE POLICY produccion_recepciones_tenant ON public.produccion_recepciones
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_recepciones_corrida
  ON public.produccion_recepciones (razon_social_id, corrida_id);

-- Registrar el modulo (debe calzar EXACTO con MODULOS de constants)
INSERT INTO public.modulos (nombre) VALUES ('Recepcion de Produccion')
ON CONFLICT (nombre) DO NOTHING;
