-- =========================================================================
-- 053 - Compra de Materiales: forma de pago (Contado/Credito) + gestion de saldo
-- =========================================================================
-- La compra de materiales (script 046) no guardaba nada de pago. Este script
-- agrega, de forma ADITIVA (mismo patron que scripts/014-cuentas-por-pagar.sql
-- sobre `gastos`):
--   * forma_pago ('Contado' | 'Credito') en el encabezado de la compra,
--   * fecha_vencimiento (para credito),
--   * monto_pagado + estado_pago ('Pendiente' | 'Parcial' | 'Pagado') para
--     llevar el saldo,
--   * tabla `materiales_compras_pagos` con los abonos (registro de pagos).
--
-- ALCANCE (decision de negocio): los abonos son un REGISTRO de saldo; NO mueven
-- caja/banco automaticamente por ahora (a diferencia de registrarPagoGasto).
-- Es el equivalente a "cuentas por pagar" para la compra de material.
--
-- Solo usa ADD COLUMN IF NOT EXISTS (nullable / con default) y CREATE TABLE IF
-- NOT EXISTS: idempotente y sin perdida de datos.
-- =========================================================================

-- 1) Campos de pago en el encabezado de la compra de material.
ALTER TABLE public.materiales_compras_encabezado
  ADD COLUMN IF NOT EXISTS forma_pago        text          NOT NULL DEFAULT 'Contado',  -- 'Contado' | 'Credito'
  ADD COLUMN IF NOT EXISTS fecha_vencimiento date,
  ADD COLUMN IF NOT EXISTS monto_pagado      numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estado_pago       text          NOT NULL DEFAULT 'Pendiente'; -- 'Pendiente' | 'Parcial' | 'Pagado'

-- Backfill: compras existentes marcadas Contado quedan como Pagado (asumimos
-- que una compra de contado ya se pago). Las de credito quedan Pendiente. Como
-- el default de forma_pago es 'Contado', las filas viejas (1 registro al
-- 2026-09-15) se consideran contado/pagadas. Solo toca filas aun en su estado
-- por defecto, para no pisar datos que el usuario ya haya ajustado.
UPDATE public.materiales_compras_encabezado
SET estado_pago = 'Pagado',
    monto_pagado = total_local
WHERE forma_pago = 'Contado'
  AND estado_pago = 'Pendiente'
  AND monto_pagado = 0;

-- 2) Abonos/pagos de la compra de material (registro de saldo, sin tesoreria).
CREATE TABLE IF NOT EXISTS public.materiales_compras_pagos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  compra_id       bigint  NOT NULL REFERENCES public.materiales_compras_encabezado(id) ON DELETE CASCADE,
  monto           numeric(14,2) NOT NULL,
  -- Texto libre e INFORMATIVO (no mueve caja/banco): 'Efectivo' | 'Banco' | 'Transferencia' | ...
  metodo          text,
  nota            text,
  fecha_pago      timestamptz NOT NULL DEFAULT now(),
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.materiales_compras_pagos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS materiales_compras_pagos_tenant ON public.materiales_compras_pagos;
CREATE POLICY materiales_compras_pagos_tenant ON public.materiales_compras_pagos
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_materiales_compras_pagos_compra
  ON public.materiales_compras_pagos (razon_social_id, compra_id);
