-- =========================================================================
-- 055 - Control de piso: operador de la corrida + paros detallados (varios)
-- =========================================================================
-- ADITIVO. Agrega:
--   * `operador` (texto libre) en `produccion_corridas`: quién corrió el lote.
--   * Tabla `produccion_corrida_paros`: varios paros por corrida, cada uno con
--     su motivo y minutos. El total de estos minutos alimenta el campo
--     `paros_minutos` de la corrida (que ya existe y usa el OEE).
--
-- Solo ADD COLUMN IF NOT EXISTS y CREATE TABLE IF NOT EXISTS: idempotente y sin
-- pérdida de datos. NO toca el resto del esquema. Requiere el script 049.
-- =========================================================================

-- 1) Operador de la corrida (texto libre).
ALTER TABLE public.produccion_corridas
  ADD COLUMN IF NOT EXISTS operador text;

-- 2) Paros detallados de una corrida (motivo + minutos). Varios por corrida.
CREATE TABLE IF NOT EXISTS public.produccion_corrida_paros (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  corrida_id      bigint  NOT NULL REFERENCES public.produccion_corridas(id) ON DELETE CASCADE,
  motivo          text,
  minutos         numeric(12,2) NOT NULL DEFAULT 0,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.produccion_corrida_paros ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_corrida_paros_tenant ON public.produccion_corrida_paros;
CREATE POLICY produccion_corrida_paros_tenant ON public.produccion_corrida_paros
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_corrida_paros_corrida
  ON public.produccion_corrida_paros (razon_social_id, corrida_id);
