-- =========================================================================
-- 056 - Produccion: Operaciones/etapas configurables por empresa (FASE 1)
-- =========================================================================
-- Cada EMPRESA define su propia SECUENCIA de operaciones (etapas) de su
-- manufactura: Operacion 1 -> 2 -> 3 ... Cada operacion tiene un nombre, una
-- posicion en la secuencia y una descripcion. Es el catalogo que la empresa
-- configura una vez; mas adelante (fase 2) cada orden de produccion recorrera
-- estas operaciones etapa por etapa (recepcion -> trabajo -> entrega).
--
-- Patron reusado: "el usuario crea su propio catalogo" (igual que
-- listas_precios / recetas). ADITIVO: solo CREATE TABLE nueva + RLS + INSERT
-- del modulo. NO toca `produccion_ordenes` ni el resto del esquema.
--
-- El modulo 'Operaciones de Produccion' nace DESHABILITADO por empresa (no va
-- en MODULOS_BASE): el super-admin lo habilita empresa por empresa desde
-- /plataforma -> Modulos. Requiere el script 017 (RLS base).
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.produccion_operaciones (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  nombre           text    NOT NULL,
  -- Posicion en la secuencia (1, 2, 3 ...). Define el orden de las etapas.
  orden_secuencia  integer NOT NULL DEFAULT 1,
  descripcion      text,
  activo           boolean NOT NULL DEFAULT true,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz
);
ALTER TABLE public.produccion_operaciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_operaciones_tenant ON public.produccion_operaciones;
CREATE POLICY produccion_operaciones_tenant ON public.produccion_operaciones
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_operaciones_secuencia
  ON public.produccion_operaciones (razon_social_id, orden_secuencia);

-- Registrar el modulo (debe calzar EXACTO con MODULOS de constants).
INSERT INTO public.modulos (nombre) VALUES ('Operaciones de Produccion')
ON CONFLICT (nombre) DO NOTHING;
