-- =========================================================================
-- 057 - Produccion: Etapas por orden (recorrido por operaciones) — FASE 2
-- =========================================================================
-- Instancia por (orden x operacion): cada orden de produccion recorre las
-- operaciones definidas por la empresa (script 056) etapa por etapa. La
-- secuencia se CONGELA al generar las etapas de la orden (snapshot de nombre y
-- posicion), de modo que cambiar la config de operaciones despues NO altera las
-- ordenes ya en curso.
--
-- Estados de etapa: Pendiente -> (Recibida | En Proceso) -> Entregada.
--   * Pendiente : aun no llega el trabajo a esta etapa.
--   * Recibida  : la etapa recibio el trabajo (recepcion): responsable + fecha.
--   * En Proceso: se esta trabajando (opcional, para distinguir del solo-recibido).
--   * Entregada : terminada; habilita RECIBIR la etapa siguiente.
--
-- ADITIVO: solo CREATE TABLE nueva + RLS. NO toca produccion_ordenes ni el resto
-- del esquema. Requiere 048 (ordenes) y 056 (operaciones).
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.produccion_orden_etapas (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id   bigint  NOT NULL,
  orden_id          bigint  NOT NULL REFERENCES public.produccion_ordenes(id) ON DELETE CASCADE,
  -- Operacion origen (referencia informativa). SET NULL si la operacion se
  -- borra del catalogo: la etapa conserva su nombre/posicion congelados.
  operacion_id      bigint  REFERENCES public.produccion_operaciones(id) ON DELETE SET NULL,
  -- Snapshot CONGELADO de la operacion al generar las etapas de la orden.
  nombre            text    NOT NULL,
  orden_secuencia   integer NOT NULL,
  estado            text    NOT NULL DEFAULT 'Pendiente',  -- Pendiente|Recibida|En Proceso|Entregada
  responsable       text,
  fecha_recepcion   timestamptz,
  fecha_entrega     timestamptz,
  cantidad_procesada numeric(14,4),
  notas             text,
  usuario           text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz,
  -- Una etapa por (orden, posicion en la secuencia).
  CONSTRAINT produccion_orden_etapas_unica UNIQUE (orden_id, orden_secuencia)
);
ALTER TABLE public.produccion_orden_etapas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_orden_etapas_tenant ON public.produccion_orden_etapas;
CREATE POLICY produccion_orden_etapas_tenant ON public.produccion_orden_etapas
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_produccion_orden_etapas_orden
  ON public.produccion_orden_etapas (razon_social_id, orden_id, orden_secuencia);

-- Registrar el modulo del tablero de flujo (calza EXACTO con MODULOS).
INSERT INTO public.modulos (nombre) VALUES ('Flujo de Produccion')
ON CONFLICT (nombre) DO NOTHING;
