-- =========================================================================
-- 059 - Ventas eliminadas (trazabilidad de facturas borradas)
-- =========================================================================
-- Cuando se elimina una factura en el Historial de Ventas, hoy se hace un
-- DELETE fisico y no queda rastro de QUE se elimino ni quien/cuando. Esta tabla
-- conserva una copia (snapshot) de la factura al momento de borrarla, para
-- auditoria y trazabilidad.
--
-- El snapshot se guarda como JSONB (encabezado + lineas + pagos) para no
-- depender de que el esquema de ventas no cambie en el futuro. Ademas se
-- copian los campos clave a columnas propias para poder listar/filtrar sin
-- abrir el JSON. `motivo` es obligatorio (lo pide la UI al eliminar).
--
-- ADITIVO: solo CREATE TABLE nueva + RLS. NO toca ventas_encabezado ni el resto.
-- Requiere el script 017 (RLS base).
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.ventas_eliminadas (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id   bigint  NOT NULL,
  -- Id original de la venta borrada (referencia informativa; la venta ya no existe).
  venta_id          bigint,
  numero_factura    text,
  cliente_id        bigint,
  cliente_nombre    text,
  fecha_venta       timestamptz,       -- fecha original de la factura
  total_venta       numeric(14,2),
  estado_pago       text,
  -- Snapshot completo: { encabezado, detalle:[...], pagos:[...] }.
  snapshot          jsonb   NOT NULL DEFAULT '{}',
  -- Trazabilidad de la eliminacion.
  motivo            text    NOT NULL,
  usuario           text,               -- quien elimino (del tenant stamp)
  eliminado_at      timestamptz NOT NULL DEFAULT now(),
  created_at        timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.ventas_eliminadas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ventas_eliminadas_tenant ON public.ventas_eliminadas;
CREATE POLICY ventas_eliminadas_tenant ON public.ventas_eliminadas
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());
CREATE INDEX IF NOT EXISTS idx_ventas_eliminadas_fecha
  ON public.ventas_eliminadas (razon_social_id, eliminado_at DESC);
