-- =========================================================================
-- 060 - Facturación CAI (comprobantes fiscales del SAR, Honduras) - FASE 1
-- =========================================================================
-- Configuracion fiscal por empresa para emitir facturas oficiales de Honduras
-- (Reglamento del Regimen de Facturacion, Acuerdo 189-2014). Esta FASE 1 solo
-- CAPTURA los datos; no cambia todavia los imprimibles (eso es la Fase 2).
--
-- El SAR autoriza rangos de correlativos POR punto de emision y POR tipo de
-- documento (01=Factura, 06=Nota de Credito, 07=Nota de Debito), cada uno con su
-- CAI, su rango [inicial..final], su correlativo actual y su fecha limite de
-- emision. Por eso la tabla lleva UNA fila por (razon_social_id, tipo_documento):
-- una empresa puede tener varias autorizaciones activas a la vez.
--
-- El correlativo visible se arma como  ESTAB-PUNTO-TIPO-NNNNNNNN, p.ej.
-- 000-001-01-00000003. Aqui guardamos las partes; el formateo lo hace la app.
--
-- Gobernanza: esta config la edita el ADMIN de la empresa (el CAI lo gestiona el
-- contribuyente ante el SAR), por eso lleva RLS por tenant (a diferencia de los
-- feature flags, que solo los toca el super-admin). El flag `facturacion_cai`
-- (razon_social_config, JSONB) es el que habilita/oculta la funcion por empresa.
--
-- ADITIVO: solo CREATE TABLE nueva + RLS + INSERT del modulo. NO toca
-- ventas_encabezado, razon_social ni el correlativo global (venta_correlativos).
-- Requiere el script 017 (funcion app_current_tenant / RLS base).
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.facturacion_cai_config (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id   bigint  NOT NULL,
  -- Tipo de documento fiscal (codigo SAR): '01' Factura, '06' Nota de Credito,
  -- '07' Nota de Debito. Texto libre por compatibilidad futura.
  tipo_documento    text    NOT NULL DEFAULT '01',
  -- Clave de Autorizacion de Impresion otorgada por el SAR.
  cai               text,
  -- Partes del correlativo fiscal (se muestran con ceros a la izquierda):
  establecimiento   text    NOT NULL DEFAULT '000',   -- 3 digitos
  punto_emision     text    NOT NULL DEFAULT '001',   -- 3 digitos
  -- Rango autorizado por el SAR (solo la parte correlativa, 8 digitos).
  rango_inicial     bigint  NOT NULL DEFAULT 1,
  rango_final       bigint  NOT NULL DEFAULT 0,
  -- Siguiente correlativo a emitir dentro del rango (lo consume la Fase 2).
  correlativo_actual bigint NOT NULL DEFAULT 1,
  -- Fecha limite de emision de la autorizacion vigente.
  fecha_limite_emision date,
  -- Datos de la imprenta (modalidad por imprenta); opcionales.
  imprenta_nombre   text,
  imprenta_rtn      text,
  imprenta_registro text,
  -- Si esta config esta activa (permite desactivar sin borrar).
  activo            boolean NOT NULL DEFAULT true,
  usuario           text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  -- Una sola config por empresa y tipo de documento.
  CONSTRAINT facturacion_cai_config_unq UNIQUE (razon_social_id, tipo_documento)
);

ALTER TABLE public.facturacion_cai_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS facturacion_cai_config_tenant ON public.facturacion_cai_config;
CREATE POLICY facturacion_cai_config_tenant ON public.facturacion_cai_config
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- Modulo nuevo (nace deshabilitado: no va en MODULOS_BASE). El nombre debe
-- calzar EXACTO con la constante en lib/constants/modulos.ts.
INSERT INTO public.modulos (nombre) VALUES ('Facturación CAI')
ON CONFLICT (nombre) DO NOTHING;
