-- =========================================================================
-- 074 - Reportería: reportes guardados (módulo opt-in por empresa)
-- =========================================================================
-- Portado de Officemart (officemart-020) al esquema `public` de EasyCount.
-- ADITIVO: una tabla nueva + índice + RLS + registro del módulo. NO toca
-- tablas ni datos existentes. Requiere `public.app_current_tenant()`
-- (scripts/017-rls-policies.sql).
--
--   reportes_guardados: configuración de un reporte de Reportería (fuente,
--     columnas y su orden, período —relativo o fijo—, filtros, agrupación,
--     medidas, orden) para volver a exportarlo a Excel. El período relativo
--     ("Este mes", "Mes anterior") se recalcula cada vez que se exporta.
--     `favorito` destaca el reporte; `exportaciones`/`ultima_exportacion`
--     llevan el conteo de uso.
--   Módulo "Reportería" (categoría propia "Reporteria" en el menú). Nace
--     DESHABILITADO (no está en MODULOS_BASE): el super-admin lo habilita por
--     empresa desde /plataforma → Módulos.
--
-- Mientras este script no se aplique, la pantalla funciona igual: guarda los
-- reportes en el navegador (localStorage) y muestra un aviso.
-- Ejecutar en el SQL editor de Supabase (service role).
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.reportes_guardados (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id      bigint  NOT NULL,
  nombre               text    NOT NULL,
  descripcion          text,
  fuente               text    NOT NULL,
  config               jsonb   NOT NULL,
  favorito             boolean NOT NULL DEFAULT false,
  exportaciones        integer NOT NULL DEFAULT 0,
  ultima_exportacion   timestamptz,
  usuario              text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz
);
CREATE INDEX IF NOT EXISTS idx_reportes_guardados_tenant
  ON public.reportes_guardados (razon_social_id, nombre);
ALTER TABLE public.reportes_guardados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS reportes_guardados_tenant ON public.reportes_guardados;
CREATE POLICY reportes_guardados_tenant ON public.reportes_guardados
  FOR ALL TO authenticated
  USING (razon_social_id = public.app_current_tenant())
  WITH CHECK (razon_social_id = public.app_current_tenant());

-- Módulo (categoría "Reporteria" en la app). Nace deshabilitado por empresa.
INSERT INTO public.modulos (nombre) VALUES ('Reportería') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
