-- =========================================================================
-- 076 - Portal de gestión interna de EasyCount (/gestion): CRM + cobros + finanzas
-- =========================================================================
-- ADITIVO. Crea 9 tablas `gestion_*` con los datos INTERNOS del negocio
-- EasyCount: las empresas que usan la app (clientes y prospectos), sus
-- mensualidades/anualidades, pagos recibidos, reuniones de venta, gastos,
-- campañas de publicidad, bitácora, notificaciones y configuración.
--
-- NO son datos de ningún tenant: no llevan razon_social_id ni política para
-- `authenticated`. RLS ENCENDIDO y SIN políticas: solo el service role
-- (server-side, portal /gestion, validado contra plataforma_admins) puede
-- leer/escribir, igual que `plataforma_admins` (script 037).
--
-- También agrega `rol` (nullable) a plataforma_admins:
--   administrador (default si es null) | ventas | contabilidad.
--
-- Los comprobantes de gastos van al bucket PRIVADO `documentos`, carpeta
-- `gestion/gastos/…`, subidos y leídos (URL firmada) con el service role: no
-- requieren políticas de Storage.
--
-- Requiere el script 037. Idempotente. Ejecutar en el SQL editor de Supabase.
-- =========================================================================

-- ── Configuración (una sola fila) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gestion_config (
  id                       smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  dias_prueba              integer NOT NULL DEFAULT 10,
  moneda                   text    NOT NULL DEFAULT 'L',
  planes                   jsonb   NOT NULL DEFAULT '[]'::jsonb,   -- [{nombre, cuota, ciclo}]
  categorias_gasto         jsonb   NOT NULL DEFAULT '["publicidad","meta_ads","google_ads","diseno","desarrollo","hosting","software","dominio","comisiones","transporte","otros"]'::jsonb,
  plantillas_recordatorio  jsonb   NOT NULL DEFAULT '[]'::jsonb,   -- [{nombre, texto}]
  updated_at               timestamptz
);
ALTER TABLE public.gestion_config ENABLE ROW LEVEL SECURITY;
INSERT INTO public.gestion_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ── Cuentas bancarias que reciben los pagos ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gestion_cuentas (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      text    NOT NULL,
  banco       text,
  moneda      text    NOT NULL DEFAULT 'HNL',
  activo      boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.gestion_cuentas ENABLE ROW LEVEL SECURITY;
INSERT INTO public.gestion_cuentas (nombre, banco, moneda)
SELECT v.nombre, v.banco, v.moneda
FROM (VALUES ('BAC Kristel', 'BAC', 'HNL'), ('BAC Sebas', 'BAC', 'HNL'), ('Sebas Colombia', NULL, 'COP'))
  AS v(nombre, banco, moneda)
WHERE NOT EXISTS (SELECT 1 FROM public.gestion_cuentas c WHERE c.nombre = v.nombre);

-- ── Empresas (clientes y prospectos; el pipeline es la misma fila) ─────────
CREATE TABLE IF NOT EXISTS public.gestion_empresas (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              text    NOT NULL,
  nombre_comercial    text,
  dueno               text,
  contacto_principal  text,
  telefono            text,
  whatsapp            text,
  correo              text,
  ciudad              text,
  pais                text    NOT NULL DEFAULT 'Honduras',
  redes               text,
  plan                text,
  cuota               numeric(14,2) NOT NULL DEFAULT 0,
  moneda              text    NOT NULL DEFAULT 'L',
  ciclo_cobro         text    NOT NULL DEFAULT 'mensual' CHECK (ciclo_cobro IN ('mensual', 'anual')),
  fecha_instalacion   date,
  fecha_inicio_prueba date,
  dia_cobro           integer CHECK (dia_cobro BETWEEN 1 AND 31),
  fecha_proximo_pago  date,
  sucursales          integer NOT NULL DEFAULT 1,
  observaciones       text,
  estado              text    NOT NULL DEFAULT 'prospecto'
                      CHECK (estado IN ('prospecto', 'reunion_pendiente', 'reunion_realizada', 'prueba', 'activo', 'pago_pendiente', 'cancelado')),
  etapa_pipeline      text    NOT NULL DEFAULT 'nuevo'
                      CHECK (etapa_pipeline IN ('nuevo', 'reunion_pendiente', 'reunion_realizada', 'prueba', 'cliente', 'no_interesado')),
  motivo_perdida      text,
  ultima_interaccion  timestamptz,
  proxima_accion      text,
  razon_social_id     bigint,                 -- empresa real en EasyCount (opcional)
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz
);
CREATE INDEX IF NOT EXISTS idx_gestion_empresas_estado ON public.gestion_empresas (estado, fecha_proximo_pago);
ALTER TABLE public.gestion_empresas ENABLE ROW LEVEL SECURITY;

-- ── Pagos recibidos ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gestion_pagos (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id              bigint NOT NULL REFERENCES public.gestion_empresas(id) ON DELETE CASCADE,
  fecha                   date   NOT NULL,
  monto                   numeric(14,2) NOT NULL,
  metodo                  text   NOT NULL DEFAULT 'transferencia' CHECK (metodo IN ('transferencia', 'efectivo', 'tarjeta', 'otro')),
  cuenta_id               bigint REFERENCES public.gestion_cuentas(id),
  referencia              text,
  observaciones           text,
  ciclo_aplicado          text   NOT NULL DEFAULT 'mensual' CHECK (ciclo_aplicado IN ('mensual', 'anual')),
  periodo_cubierto_desde  date,
  periodo_cubierto_hasta  date,
  usuario                 text,
  created_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gestion_pagos_fecha   ON public.gestion_pagos (fecha);
CREATE INDEX IF NOT EXISTS idx_gestion_pagos_empresa ON public.gestion_pagos (empresa_id, fecha DESC);
ALTER TABLE public.gestion_pagos ENABLE ROW LEVEL SECURITY;

-- ── Reuniones de venta ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gestion_reuniones (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id      bigint NOT NULL REFERENCES public.gestion_empresas(id) ON DELETE CASCADE,
  contacto        text,
  fecha           date   NOT NULL,
  hora            time,
  tipo            text   NOT NULL DEFAULT 'videollamada' CHECK (tipo IN ('presencial', 'videollamada', 'llamada')),
  estado          text   NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('confirmada', 'pendiente', 'reprogramada')),
  resultado       text   CHECK (resultado IS NULL OR resultado IN ('interesado', 'quiere_prueba', 'debe_consultarlo', 'no_interesado', 'seguimiento', 'cliente_confirmado')),
  motivo_perdida  text   CHECK (motivo_perdida IS NULL OR motivo_perdida IN ('precio', 'no_lo_necesita', 'usa_otro_sistema', 'sin_presupuesto', 'no_respondio', 'funcionalidad_faltante', 'decision_socios', 'otro')),
  notas           text,
  proximo_paso    text,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz,
  -- El motivo de pérdida es obligatorio SOLO cuando el resultado es "no interesado".
  CONSTRAINT gestion_reuniones_motivo_chk CHECK (resultado IS DISTINCT FROM 'no_interesado' OR motivo_perdida IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_gestion_reuniones_fecha ON public.gestion_reuniones (fecha, hora);
ALTER TABLE public.gestion_reuniones ENABLE ROW LEVEL SECURITY;

-- ── Gastos del negocio ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gestion_gastos (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha             date   NOT NULL,
  categoria         text   NOT NULL DEFAULT 'otros',
  descripcion       text,
  monto             numeric(14,2) NOT NULL,
  metodo            text,
  comprobante_path  text,                     -- bucket documentos: gestion/gastos/…
  observaciones     text,
  usuario           text,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gestion_gastos_fecha ON public.gestion_gastos (fecha);
ALTER TABLE public.gestion_gastos ENABLE ROW LEVEL SECURITY;

-- ── Campañas de publicidad ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gestion_campanas (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                text   NOT NULL,
  plataforma            text   NOT NULL DEFAULT 'otros',
  fecha_inicio          date,
  fecha_fin             date,
  monto_invertido       numeric(14,2) NOT NULL DEFAULT 0,
  prospectos_generados  integer NOT NULL DEFAULT 0,
  reuniones_generadas   integer NOT NULL DEFAULT 0,
  clientes_obtenidos    integer NOT NULL DEFAULT 0,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz
);
ALTER TABLE public.gestion_campanas ENABLE ROW LEVEL SECURITY;

-- ── Bitácora por empresa (automática + notas manuales) ─────────────────────
CREATE TABLE IF NOT EXISTS public.gestion_actividades (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id   bigint NOT NULL REFERENCES public.gestion_empresas(id) ON DELETE CASCADE,
  tipo         text   NOT NULL,   -- creada | instalada | fin_prueba | activada | pago | estado | reunion | nota | etapa
  descripcion  text,
  fecha        timestamptz NOT NULL DEFAULT now(),
  usuario      text
);
CREATE INDEX IF NOT EXISTS idx_gestion_actividades_empresa ON public.gestion_actividades (empresa_id, fecha DESC);
ALTER TABLE public.gestion_actividades ENABLE ROW LEVEL SECURITY;

-- ── Notificaciones (generadas al cargar; `clave` evita duplicados) ─────────
CREATE TABLE IF NOT EXISTS public.gestion_notificaciones (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave       text    NOT NULL UNIQUE,   -- p.ej. pago_hoy:12:2026-10-05
  tipo        text    NOT NULL,
  empresa_id  bigint REFERENCES public.gestion_empresas(id) ON DELETE CASCADE,
  mensaje     text    NOT NULL,
  fecha       date    NOT NULL,
  leida       boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gestion_notificaciones_leida ON public.gestion_notificaciones (leida, fecha DESC);
ALTER TABLE public.gestion_notificaciones ENABLE ROW LEVEL SECURITY;

-- ── Rol del super-admin en el portal (nullable = administrador) ────────────
ALTER TABLE public.plataforma_admins ADD COLUMN IF NOT EXISTS rol text;

NOTIFY pgrst, 'reload schema';
