-- =========================================================================
-- 077 - Portal /gestion: socios, gastos pagados por socio y liquidaciones
-- =========================================================================
-- ADITIVO. Requiere el script 076.
--
--   gestion_socios: socios de EasyCount con su % de participación. La suma de
--     los % de los socios activos no debe pasar de 100 (lo valida la app); lo
--     que falte para 100 se queda en EasyCount.
--   gestion_gastos.socio_id (NUEVA, nullable, sin constraints): quién pagó el
--     gasto. NULL = lo pagó EasyCount; un id = lo asumió ese socio de su bolsa
--     y se le reembolsa en su liquidación.
--   gestion_liquidaciones: pagos hechos a un socio a cuenta de lo que se le
--     debe (lo devengado se calcula cada mes; esto registra lo ya pagado).
--
-- Liquidación del mes (lib/gestion/socios.ts):
--   utilidad = ingresos − TODOS los gastos del mes
--   socio    = % × utilidad + gastos que pagó ese socio
--   EasyCount se queda con (100 − Σ%) × utilidad.
--
-- Tablas con RLS encendido y SIN políticas (solo service role), igual que 076.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.gestion_socios (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      text    NOT NULL,
  porcentaje  numeric(5,2) NOT NULL DEFAULT 0 CHECK (porcentaje >= 0 AND porcentaje <= 100),
  correo      text,
  notas       text,
  activo      boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz
);
ALTER TABLE public.gestion_socios ENABLE ROW LEVEL SECURITY;

-- Quién pagó el gasto (NULL = EasyCount). Nullable y sin constraints → instantáneo.
ALTER TABLE public.gestion_gastos ADD COLUMN IF NOT EXISTS socio_id bigint;

CREATE TABLE IF NOT EXISTS public.gestion_liquidaciones (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id    bigint NOT NULL REFERENCES public.gestion_socios(id) ON DELETE CASCADE,
  fecha       date   NOT NULL,
  monto       numeric(14,2) NOT NULL CHECK (monto > 0),
  periodo     text,                 -- 'YYYY-MM' al que se aplica (opcional, informativo)
  cuenta_id   bigint REFERENCES public.gestion_cuentas(id),
  notas       text,
  usuario     text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gestion_liquidaciones_socio ON public.gestion_liquidaciones (socio_id, fecha DESC);
ALTER TABLE public.gestion_liquidaciones ENABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
